"""init

Revision ID: 933502080b98
Revises: 
Create Date: 2026-01-22 00:48:06.380289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '933502080b98'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('query')
    # ### end Alembic commands ###
